name: GitHub Actions Demo2
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: 
  push:

jobs:
  Job-One:
    name: Job-One
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The workflow definition resides in main"
      - if: ${{ github.event_name == 'workflow_dispatch' }}
        run: echo "str_param default defined ${{ inputs.str_param }}"
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - name: Get push event details
        if: ${{ github.event_name == 'push' }}
        run: |
          echo "Pusher: ${{ github.event.pusher.name }}"
  Job-two:
    name: Job / two
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The workflow definition resides in main"         
  
